name: CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Netlify Deployment
        run: |
          curl -X POST ${{ secrets.NETLIFY_BUILD_HOOK }}

      - name: Confirmation
        run: |
          echo "Deployment completed at $(date)"
